(MainThread) 190906_11:36:54.246 DEBUG Trading.py:133 now is 2019-09-06 11:36:54.246431
(MainThread) 190906_11:36:57.200 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfarm.nj
(MainThread) 190906_11:36:57.202 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:cashfarm
(MainThread) 190906_11:36:57.204 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfarm
(MainThread) 190906_11:36:57.206 ERROR wrapper.py:56 ERROR -1 2106 HMDS data farm connection is OK:ushmds
(MainThread) 190906_11:37:04.948 ERROR wrapper.py:56 ERROR -1 2108 Market data farm connection is inactive but should be available upon demand.cashfarm
(MainThread) 190906_11:37:04.949 ERROR wrapper.py:56 ERROR -1 2108 Market data farm connection is inactive but should be available upon demand.cashfarm
(Thread-1) 190906_11:37:05.079 ERROR reader.py:52 unhandled exception in EReader thread
Traceback (most recent call last):
  File "d:\py\tms\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "d:\py\tms\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "d:\py\tms\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
(Thread-2) 190906_11:37:28.488 ERROR wrapper.py:56 ERROR 3 504 Not connected
(Thread-2) 190906_11:37:38.067 ERROR wrapper.py:56 ERROR 4 504 Not connected
